src/Entity/Department.php
<?php
declare(strict_types=1);

namespace App\Entity;

class Department
{
	private ?int $id;
	private string $city;
	private string $address;

	/**
	 * @var Worker[]
	 */
	private array $workers;

	/**
	 * @param ?int $id
	 * @param string $city
	 * @param string $address
	 * @param Worker[] $workers
	 */
	public function __construct(?int $id, string $city, string $address, array $workers)
	{
		if ($city === '')
		{
			throw new \InvalidArgumentException("City cannot be empty");
		}

		if ($address === '')
		{
			throw new \InvalidArgumentException("Address cannot be empty");
		}

		$this->id = $id;
		$this->city = $city;
		$this->address = $address;
		$this->workers = $workers;
	}

	/**
	 * @return ?int
	 */
	public function getId(): ?int
	{
		return $this->id;
	}

	/**
	 * @return string
	 */
	public function getAddress(): string
	{
		return $this->address;
	}

	/**
	 * @return string
	 */
	public function getCity(): string
	{
		return $this->city;
	}

	/**
	 * @return Worker[]
	 */
	public function getWorkers(): array
	{
		return $this->workers;
	}

	public function getWorkersCount(): int
	{
		return count($this->workers);
	}
}

src/Controller/DepartmentController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\Entity\Department;
use App\Repository\DepartmentDAO;
use App\Repository\DepartmentRepository;
use App\Repository\WorkerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Dotenv\Dotenv;

(new Dotenv())->load(__DIR__ . '/../../.env');

class DepartmentController extends AbstractController
{
	private DepartmentDAO $departmentDAO;
	private DepartmentRepository $departmentRepository;
	private WorkerRepository $workerRepository;

	public function __construct(
		DepartmentDAO $departmentDAO,
		DepartmentRepository $departmentRepository,
		WorkerRepository $workerRepository
	) {
		$this->departmentDAO = $departmentDAO;
		$this->departmentRepository = $departmentRepository;
		$this->workerRepository = $workerRepository;
	}

	/**
	 * @throws \Exception
	 */
	public function showDepartmentPage(int $departmentId): Response
	{
		$department = $this->departmentRepository->findById($departmentId);
		if (!$department)
		{
			throw new \InvalidArgumentException("The department with id = " . $departmentId . " does not exist");
		}
		$workers = $this->workerRepository->findWorkersByDepartmentId($departmentId);
		return $this->render('department/departmentCard.html.twig', [
			'department' => $department,
			'workers' => $workers
		]);
	}

	/**
	 * @throws \Exception
	 */
	public function showEditDepartmentPage(int $departmentId): Response
	{
		$department = $this->departmentRepository->findById($departmentId);
		return $this->render('department/departmentAdd.html.twig', [
			'department' => $department
		]);
	}

	public function editDepartment(Request $request, int $departmentId): Response
	{
		$department = new Department(
			id: $departmentId,
			city: $request->get('city'),
			address: $request->get('address'),
		);
		$this->departmentRepository->save($department);
		return $this->redirectToRoute('departments_page', []);
	}

	public function showAddDepartmentPage(): Response
	{
		return $this->render('department/departmentAdd.html.twig', []);
	}

	public function addDepartment(Request $request): Response
	{
		$newDepartment = new Department(
			null,
			$request->get('city'),
			$request->get('address'),
		);
		$id = $this->departmentRepository->save($newDepartment);
		return $this->redirectToRoute('department_page', [
			'departmentId' => $id,
		]);
	}

	/**
	 * @throws \Exception
	 */
	public function deleteDepartment(int $departmentId): Response
	{
		$this->departmentRepository->deleteById($departmentId);
		$departmentsData = $this->departmentDAO->listAll();
		return $this->render('department/departments.html.twig', [
			'departments' => $departmentsData,
		]);
	}

	/**
	 * @throws \Exception
	 */
	public function index(): Response
	{
		$departmentsData = $this->departmentDAO->listAll();
		return $this->render('department/departmentList.html.twig', [
			'departments' => $departmentsData,
		]);
	}
}

templates/department/departmentAdd.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Worker{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/css/departmentAdd.css"/>
    <link rel="stylesheet" href="/css/departmentList.css"/>
{% endblock %}

{% block body %}
<section class="add-department-form">
    <h1 class="department-list__title">
        <a href="{{ path('departments_page') }}" class="bread-crumbs pointer">Филиалы</a> >
        {% if app.request.get('_route') == 'edit_department_page' %}Редактирование филиала
        {% elseif app.request.get('_route') == 'add_affiliate_page' %}Добавление филиала
        {% endif %}
    </h1>
    <form method="post" action="/department/{{ department is defined ? 'edit/' ~ department.id : 'add' }}">
        <div class="add-department-form__row">
            <label class="add-department-form__label" for="city">Город</label>
            <input
                    class="add-department-form__input"
                    name="city"
                    id="city"
                    type="text"
                    value="{{ department is defined ? department.city : '' }}"

            />
        </div>
        <div class="add-department-form__row">
            <label class="add-department-form__label" for="address">Адрес</label>
            <input
                    class="add-department-form__input"
                    name="address"
                    id="address"
                    type="text"
                    value="{{ department is defined ? department.address : '' }}"
            />
        </div>
        <input class="add-department-form__add-button button" type="submit" value="{% if app.request.get('_route') == 'edit_department_page' %}Обновить{% elseif app.request.get('_route') == 'add_affiliate_page' %}Добавить{% endif %}">
    </form>
</section>
{% endblock %}

templates/department/departmentCard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Department List{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="/css/departmentList.css"/>
{% endblock %}

{% block javascripts %}
    <script type="application/javascript" src="/js/worker.js" defer></script>
{% endblock %}

{% block body %}
<section class="department-list">
    <div class="department-list__header">
        <h1 class="department-list__title">
            <a href="{{ path('departments_page') }}" class="bread-crumbs pointer">Филиалы</a> > {{ department.city }}, {{ department.address }}
        </h1>
        <button onclick="location.href='/worker/add/{{ department.id }}';" class="department-list__add-button">Добавить работника</button>
    </div>
    <table class="department-list__table">
        <thead class="department-list__table-header">
        <tr class="department-list__row">
            <th class="department-list__full-name">ФИО</th>
            <th class="department-list__job-title">Должность</th>
            <th class="department-list__edit-button"></th>
            <th class="department-list__delete-button"></th>
        </tr>
        </thead>
        <tbody id="tbody">
        {% include '/department/workers.html.twig' %}
        </tbody>
    </table>
</section>
{% endblock %}

templates/department/departmentList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Department List{% endblock %}

{% block javascripts %}
	<script type="application/javascript" src="/js/department.js" defer></script>
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="/css/departmentList.css"/>
{% endblock %}

{% block body %}
	<section class="department-list">
		<div class="department-list__header">
			<h1 class="department-list__title">Филиалы</h1>
			<button id="addButton" onclick="location.href='./department/add';" class="department-list__add-button">Добавить филиал
			</button>
		</div>
		<table class="department-list__table">
			<thead class="department-list__table-header">
			<tr class="department-list__row">
				<th class="department-list__city">Город</th>
				<th class="department-list__address">Адрес</th>
				<th class="department-list__workers-count">Количество сотрудников</th>
				<th class="department-list__edit-button"></th>
				<th class="department-list__delete-button"></th>
			</tr>
			</thead>
			<tbody id="tbody">
			{% include '/department/departments.html.twig' %}
			</tbody>
		</table>
	</section>
{% endblock %}

templates/department/departments.html.twig
{% for department in departments %}
<tr onclick="location.href = '/department/{{ department.id }}'" class="department-list__row department-list__row_pointer">
    <td class="department-list__city">{{ department.city }}</td>
    <td class="department-list__address">{{ department.address }}</td>
    <td class="department-list__workers-count">{{ department.workersCount }}</td>
    <td class="department-list__edit-button">
        <button data-department-id="{{ department.id }}" class="button edit-button"><img src="/edit_button.svg" alt="edit button"/></button>
    </td>
    <td class="department-list__delete-button">
        <button data-department-id="{{ department.id }}" class="button delete-button">
            <img src="/delete_button.svg" alt="delete button"/>
        </button>
    </td>
</tr>
{% endfor %}

templates/department/workers.html.twig
{% for worker in workers %}
    <tr onclick="location.href = '/worker/{{ worker.id }}'" class="department-list__row department-list__row_pointer">
        <td class="department-list__full-name">{{ worker.fullName }}</td>
        <td class="department-list__job-title">{{ worker.jobTitle }}</td>
        <td class="department-list__edit-button">
            <button data-department-id="{{ worker.departmentId }}"  data-worker-id="{{ worker.id }}" class="edit-button button"><img src="/edit_button.svg"  alt="edit button"/></button>
        </td>
        <td class="department-list__delete-button">
            <button data-worker-id="{{ worker.id }}" class="delete-button button"><img src="/delete_button.svg"  alt="delete button"/></button>
        </td>
    </tr>
{% endfor %}